import type { Metadata } from "next";
import "./globals.css";
import VideoLazyLoad from "@/scripts/Video_Load";

export const metadata: Metadata = {
  title: "Creon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
