"use client";

import DropDown from "@/components/Widgets/DropDown";
import Image from "next/image";
import React, { useState } from "react";
import bg from "@/public/images/mission-bg.webp";

const Data = [
  {
    title: "Profitability and Growth",
    content:
      "At Creon, we handpick cutting-edge AI projects and offer our community and token holders early access and investment opportunities. Our community actively contributes to the growth and profitability of these projects, creating a dynamic ecosystem of innovation and shared success.",
    icon: "https://ucarecdn.com/f623e584-cc54-4705-a841-69df9a06a775/",
  },
  {
    title: "Transparent & Fair Decentralized Earnings",
    content:
      "Thanks to the integration of the CREON NFT Pass, users are given a direct stake in the profits generated by AI tools and projects. This initiative overturns the traditional profit models by putting the community first, allowing them to benefit from the collective use of AI applications.",
    icon: "https://ucarecdn.com/67396a88-40fa-4e66-92cd-be697f9d1dd1/",
  },
  {
    title: "Launching the future",
    content:
      "The Creon AI Launchpad represents a groundbreaking opportunity in the realm of AI and blockchain. It is the first known platform for acquiring allocations in tokenized AI projects, offering our community of NFT and CREON token holders early access to innovative AI endeavors.",
    icon: "https://ucarecdn.com/9f8d5f22-7a0f-424c-b5fd-eb8e023e76f6/",
  },
  {
    title: "Limitless Possibilities of AI & Crypto",
    content:
      "The integration of AI and cryptocurrencies presents limitless possibilities, and as pioneers, we embrace the challenges and the extraordinary rewards. Creon isn't just about profiting from technology; it's about actively shaping the future of innovation.",
    icon: "https://ucarecdn.com/fc2cecb1-b24a-4976-9ae7-07b9f73214d6/",
  },
];

function OurMission() {
  const [activeIndex, setActiveIndex] = useState<number | null>(null);

  const handleToggle = (index: number) => {
    setActiveIndex((prevIndex) => (prevIndex === index ? null : index));
  };

  return (
    <section>
      <div
        className="min-h-[910px] xl:w-[75%] w-[90%] mx-auto text-white flex flex-col md:flex-row lg:gap-10 gap-2 relative pt-20"
      >
        <div className="lg:w-[60%] md:w-[45%] w-full z-10">
          <h3 className="xl:text-[2.6rem] 2xl:text-[2.5vw] sm:text-[3vw] text-[4.5vw] font-Monument uppercase leading-[110%] z-10 mt-10">
            OUR VISION IS TO SUPPORT THE INNOVATION OF AI BLOCKCHAIN PROJECTS
            <span className="bg-gradient-to-r from-blue-500 to-purple-600 bg-clip-text text-transparent">
              {" "}
              WHILE PRIORITIZING COMMUNITIES AND DEMOCRATIZING PROFITS
            </span>
          </h3>
        </div>

        <div className="flex flex-col gap-5 lg:w-[40%] md:w-[55%] sm:w-[70%] w-[99%] z-10 mt-10">
          {Data &&
            Data.map((content, index) => (
              <div
                key={index}
              >
                <DropDown
                  icon={content.icon}
                  title={content.title}
                  content={content.content}
                  isOpen={activeIndex === index}
                  onToggle={() => handleToggle(index)}
                />
              </div>
            ))}
        </div>

        <Image
          src={bg}
          alt="Creon logo"
          className="absolute xl:bottom-0 md:bottom-[200px] lg:left-[40%] md:left-[20%] md:-translate-x-1/2 sm:-right-[150px] bottom-0 -right-[100px] xl:w-[40vw] lg:w-[45vw] sm:w-[70%] w-[90%] z-0"
        />
      </div>
    </section>
  );
}

export default OurMission;
